import {Inter} from "next/font/google";
import "../Style/globals.css";

const font = Inter({subsets: ["latin"]});

export const metadata = {
    title: "Json-Generator",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="tr">
        <body className={font.className}>{children}</body>
        </html>
    );
}
